### ISSUE TITLE
How to test the performance of PoE and PBFT

### ISSUE THREAD

**Issue by StoneLing** [apache/incubator-resilientdb#144]
I have tried to run  ./performance/poe_performance.sh config/kv_performance_server.conf but cannot get the results,  the results shown below: getting results
scp -i /home/ubuntu/.ssh/guigu_bft.pem ubuntu@172.26.0.3:/home/ubuntu/.log ./172.26.0.3_log
scp: /home/ubuntu/.log: No such file or directory
scp -i /home/ubuntu/.ssh/guigu_bft.pem ubuntu@172.26.0.3:/home/ubuntu/.log ./172.26.0.3_log
scp: /home/ubuntu/.log: No such file or directory
scp -i /home/ubuntu/.ssh/guigu_bft.pem ubuntu@172.26.0.3:/home/ubuntu/.log ./172.26.0.3_log
scp: /home/ubuntu/.log: No such file or directory
scp -i /home/ubuntu/.ssh/guigu_bft.pem ubuntu@172.26.0.3:/home/ubuntu/.log ./172.26.0.3_log
scp: /home/ubuntu/.log: No such file or directory
scp -i /home/ubuntu/.ssh/guigu_bft.pem ubuntu@172.26.0.3:/home/ubuntu/.log ./172.26.0.3_log
scp: /home/ubuntu/.log: No such file or directory
ls: cannot access 'result_*_log': No such file or directory
Traceback (most recent call last):
  File "performance/calculate_result.py", line 70, in <module>
    cal_tps(tps)
  File "performance/calculate_result.py", line 44, in cal_tps
    print("average throughput:",sum(tps_sum)/len(tps_sum))
ZeroDivisionError: division by zero
save result to results.log
calculate results, number of nodes: 0
max throughput: 0

**Comment by HanBoZh1** [comment]
May I ask how you solved this problem?
