### ISSUE TITLE
LICENSE has incorrect third party information

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-resilientdb#147]
The LICENSE should be the standard Apache License but if you have 3rd party source code included in your code base, you must also list the affected files. You must provide the licensing information about that 3rd party source too.

Examples:
https://github.com/apache/fury/blob/main/LICENSE
https://github.com/apache/spark/blob/master/LICENSE

Your LICENSE file lists 3rd party libraries. Those should not be in your LICENSE file. Projects sometimes have binary artifacts that they release with the source releases. These binary artifacts should have LICENSE files and they will typically have the standard Apache License plus a list of the 3rd party libs that are in the binary artifact with their license details. Many projects put this sort of info in a file called LICENSE-binary. ResilientDB does not appear to be releasing binary artifacts at the moment so this is not strictly needed. But the info is useful for people you download your source release because it tells them what to expect when they run the install script. So creating a LICENSE-binary may still be a useful thing to do. Your currently incorrect LICENSE file may be a good starting point for creating a LICENSE-binary file.

Example:
https://github.com/apache/spark/blob/master/LICENSE-binary

**Comment by CalvinKirs** [comment]
@cjcchen https://github.com/apache/incubator-resilientdb/blob/master/LICENSE#L239-L293 Could you help confirm whether our source code references these components? If not, we should remove these licenses.

**Comment by cjcchen** [comment]
Hi all,

I have removed those components from LICENSE file.
We also don't have any 3rd-binary.


Thanks,
Junchao

**Comment by cjcchen** [comment]
fixed
