### ISSUE TITLE
large number of files with no Apache source header

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-resilientdb#148]
This can easily lead to -1s on release votes

Found with Apache Rat. https://creadur.apache.org/rat/

  ./.bazelrc
  ./.bazelversion
  ./.clang-format
  ./.gitignore
  ./.licenserc.yaml
  ./CHANGELOG.md
  ./CNAME
  ./CODE_OF_CONDUCT.md
  ./DISCLAIMER-WIP
  ./README.md
  ./WORKSPACE
  ./bazel.gpg
  ./repositories.bzl
  ./Docker/Dockerfile
  ./Docker/Dockerfile_mac
  ./api/README.md
  ./api/ip_address.config
  ./documents/doxygen/.gitignore
  ./documents/doxygen/Doxyfile
  ./documents/doxygen/DoxygenLayout.xml
  ./documents/doxygen/doxygen_html_style.css
  ./documents/doxygen/header
  ./documents/file/prometheus.yml
  ./monitoring/README.md
  ./monitoring/prometheus/prometheus.yml
  ./platform/consensus/ordering/geo_pbft/README.md
  ./platform/consensus/ordering/pbft/README.md
  ./platform/networkstrate/README.md
  ./platform/statistic/README.md
  ./platform/test/test_data/kv_config.config
  ./platform/test/test_data/server.config
  ./scripts/deploy/README.md
  ./scripts/deploy/config/key_example.conf
  ./scripts/deploy/config/kv_performance_server.conf
  ./scripts/deploy/config/kv_server.conf
  ./scripts/deploy/config/poe.config
  ./scripts/deploy/config/template.config
  ./scripts/deploy/data/cert/node6.key.key.pri
  ./scripts/deploy/data/cert/node6.key.key.pub
  ./scripts/deploy/data/cert/node6.key.pri
  ./scripts/deploy/data/cert/node6.key.pub
  ./scripts/deploy/data/cert/node7.key.key.pri
  ./scripts/deploy/data/cert/node7.key.key.pub
  ./scripts/deploy/data/cert/node7.key.pri
  ./scripts/deploy/data/cert/node7.key.pub
  ./scripts/deploy/data/cert/node8.key.key.pri
  ./scripts/deploy/data/cert/node8.key.key.pub
  ./scripts/deploy/data/cert/node8.key.pri
  ./scripts/deploy/data/cert/node8.key.pub
  ./scripts/deploy/data/cert/node9.key.key.pri
  ./scripts/deploy/data/cert/node9.key.key.pub
  ./scripts/deploy/data/cert/node9.key.pri
  ./scripts/deploy/data/cert/node9.key.pub
  ./service/tools/config/interface/service.config
  ./service/tools/config/interface/service0.config
  ./service/tools/config/server/server.config
  ./service/tools/config/server/utxo_config.config
  ./service/tools/contract/README.md
  ./service/tools/contract/api_tools/client_config.config
  ./service/tools/contract/api_tools/config/server_config.config
  ./service/tools/contract/api_tools/example_contract/token.sol
  ./service/tools/data/cert/node6.key.key.pri
  ./service/tools/data/cert/node6.key.key.pub
  ./service/tools/data/cert/node6.key.pri
  ./service/tools/data/cert/node6.key.pub
  ./service/tools/data/cert/node7.key.key.pri
  ./service/tools/data/cert/node7.key.key.pub
  ./service/tools/data/cert/node7.key.pri
  ./service/tools/data/cert/node7.key.pub
  ./service/tools/data/cert/node8.key.key.pri
  ./service/tools/data/cert/node8.key.key.pub
  ./service/tools/data/cert/node8.key.pri
  ./service/tools/data/cert/node8.key.pub
  ./service/tools/data/cert/node9.key.key.pri
  ./service/tools/data/cert/node9.key.key.pub
  ./service/tools/data/cert/node9.key.pri
  ./service/tools/data/cert/node9.key.pub
  ./service/tools/utxo/README.md
  ./service/tools/utxo/wallet_tool/cpp/client_config.config
  ./service/tools/utxo/wallet_tool/cpp/server_config0.config
  ./service/utxo/config/server_config.config
  ./service/utxo/config/utxo_config.config
  ./third_party/asio.BUILD
  ./third_party/civetweb.BUILD
  ./third_party/crow.BUILD
  ./third_party/date.BUILD
  ./third_party/eEVM.BUILD
  ./third_party/json.BUILD
  ./third_party/leveldb.BUILD
  ./third_party/prometheus.BUILD
  ./third_party/rapidjson.BUILD
  ./third_party/snappy.BUILD
  ./third_party/z.BUILD
  ./third_party/zlib.BUILD
  ./third_party/loc_script/action.yml
  ./third_party/loc_script/src/index.js

**Comment by cjcchen** [comment]
fixed.
