### ISSUE TITLE
The download section in UI omits the asc signature.

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-resilientdb#159]
<img width="683" alt="Screenshot 2024-10-06 at 20 45 24" src="https://github.com/user-attachments/assets/9eebf89e-32f5-4ef7-8199-384fe3bfcfd6">

The asc signature is an absolute requirement for any ASF project.

@cjcchen could you look at this?

**Comment by pjfanning** [comment]
<img width="588" alt="image" src="https://github.com/user-attachments/assets/c11c8699-c85b-4ed9-8ae3-79b43fd46ce8">

Worse news still @cjcchen - the 'zip' download omits both the asc and sha512 links.

**Comment by apratimshukla6** [comment]
The website is now updated with the ASC signature and the .zip is now removed.
![image](https://github.com/user-attachments/assets/2c937a72-a41d-47c8-a200-00a5433738b0)
