### ISSUE TITLE
last source release is a directory with the wrong name

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-resilientdb#160]
https://dist.apache.org/repos/dist/release/incubator/resilientdb/1.10.0-rc3/

this should be

https://dist.apache.org/repos/dist/release/incubator/resilientdb/1.10.0-rc3/

* pre-release RCs should have directory names like 1.10.0-rc3
* when the vote passes, the RC is copied to the release are (https://dist.apache.org/repos/dist/release) but the directory should be renamed to remove the `-rc3` suffix.

**Comment by cjcchen** [comment]
renamed it
https://dist.apache.org/repos/dist/release/incubator/resilientdb/1.10.0
