### ISSUE TITLE
old RCs should be removed from dist.apache.org

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-resilientdb#161]
https://dist.apache.org/repos/dist/dev/incubator/resilientdb/

Still contains an RC2 that was not released.

@cjcchen can you remove this?

**Comment by cjcchen** [comment]
https://dist.apache.org/repos/dist/dev/incubator/resilientdb/
removed

**Comment by pjfanning** [comment]
@cjcchen Can you remove the KEYS file from the dev folder too? You should only have the KEYS file in the releases folder.

**Comment by cjcchen** [comment]
@pjfanning 
Removed.
https://dist.apache.org/repos/dist/dev/incubator/resilientdb/

I also added a 1.10.1-rc0 to remove the binary from 1.10.0.
